log_format metrics "$proxy_host$request_uri $request_body";
access_log /dev/stdout metrics;
rewrite_log on;

proxy_cache_path /var/cache/nginx/main_cache levels=1:2 keys_zone=main_cache:100m max_size=1g inactive=10080m;
proxy_ignore_headers Expires Cache-Control;
proxy_cache_methods GET HEAD POST;

# locks all clients that request the same asset till the first is cached
proxy_cache_lock on;

# try to recover from upstream errors
proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;

server {
  listen 80;

  add_header X-Vamonos-Mgp-Cache-Status $upstream_cache_status;
  server_name "vamonos-mgp-proxy.fly.dev";

  location /providers/mgp/ {
    rewrite ^/providers/mgp(.*)$ $1 break;

    proxy_pass https://appsl.mardelplata.gob.ar;
    proxy_cache_key "$proxy_host$request_uri $request_body";
    proxy_ssl_server_name on;
    proxy_cache main_cache;
    proxy_cache_valid any 1m;
  }

  location /map_tiles/osm/ {
    rewrite ^/map_tiles/osm(.*)$ $1 break;

    proxy_pass https://tile.openstreetmap.org;
    proxy_cache main_cache;
    proxy_cache_valid any 7d;
  }
}